services:
  69-s3-db:
    image: postgres:16
    container_name: 69-s3-db
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd*10"
      POSTGRES_USER: jeerapol
      POSTGRES_DB: jeerapol
    ports:
      - "54327:5432"
    networks:
      - s3-net

networks:
  s3-net:
    external: true
