services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - 54327:5432
    entrypoint:
      - POSTGRES_PASSWORD=P@ssw0rd*10
      - POSTGRES_USER=jeerapol
      - POSTGRES_DB=jeerapol
